---
- name: Install MariaDB
  apt: name={{ item }} state=present
  with_items:
  - mariadb-server

- name: Start MariaDB
  service: name=mysql state=started

- name: Install MariaDB User aa_db
  mysql_user: name=aa_db host=% password= priv=*.*:ALL,GRANT state=present
  notify:
  - Restart MariaDB

- name: Install MariaDB Config Overrides
  template: src=../templates/mysql-000-bind-address.cnf.j2 dest=/etc/mysql/conf.d/000-bind-address.cnf owner=root group=root
  notify:
  - Restart MariaDB
